export const SET_MAIN_PAGE_SELECT_DATA_SOURCE = 'SET_MAIN_PAGE_SELECT_DATA_SOURCE';
export const SET_MAIN_PAGE_SELECT_2_DATA_SOURCE = 'SET_MAIN_PAGE_SELECT_2_DATA_SOURCE';
export const SET_MAIN_PAGE_SELECT_3_DATA_SOURCE = 'SET_MAIN_PAGE_SELECT_3_DATA_SOURCE';
